//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace копировальный_центр
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int id { get; set; }
        public int idClient { get; set; }
        public string Orders1 { get; set; }
        public string address { get; set; }
        public string status { get; set; }
        public Nullable<int> price { get; set; }
    
        public virtual Clients Clients { get; set; }
    }
}
